
import "@/app/globals.css";

export const metadata = {
  title: "admin: Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <h2>Admin Navbar</h2>
        <br />
        {children}
        <br />
        <h2>Admin Footer</h2>
      </body>
    </html>
  );
}
