
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer"

export const metadata = {
  title: "Main app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
