
import "@/app/globals.css";

export const metadata = {
  title: "admin: login app",
  description: "Generated by create next app",
};

export default function AdminloginLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        
        <span>login navbar</span>
        {children}
        
      </body>
    </html>
  );
}
